provider: openrouter
#model:    qwen/qwen3-235b-a22b:free
#model:     deepseek/deepseek-chat-v3-0324:free
model:      meta-llama/llama-3.3-70b-instruct:free
providers:
  openrouter:
    name:     openrouter
    baseURL:  https://openrouter.ai/api/v1
    envKey:   OPENROUTER_API_KEY
